name: Sync to CNB
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part:
          - android_webview
          - apps
          - ash
          - base
          - build
          - build_overrides
          - buildtools
          - cc
          - chrome
          - chromecast
          - chromeos
          - clank
          - codelabs
          - components
          - content
          - crypto
          - dbus
          - device
          - docs
          - extensions
          - fuchsia_web
          - gin
          - google_apis
          - gpu
          - headless
          - infra
          - internal
          - ios
          - ios_internal
          - ipc
          - media
          - mojo
          - net
          - pdf
          - ppapi
          - printing
          - remoting
          - rlz
          - sandbox
          - services
          - signing_keys
          - skia
          - sql
          - storage
          - styleguide
          - testing
          - third_party
          - tools
          - ui
          - url
          - v8
          - webkit/data

    steps:
      - name: Sparse Checkout ${{ matrix.part }}
        run: |
          git init
          git remote add origin https://github.com/wubonetcn/chromium.git
          git config core.sparseCheckout true
          echo "${{ matrix.part }}" >> .git/info/sparse-checkout
          git fetch --depth=1 origin main
          git checkout main
      
      - name: Sync ${{ matrix.part }} to CNB Repository
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/${{ secrets.GIT_TARGET }}.git" \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="cnb" \
            -e PLUGIN_PASSWORD=${{ secrets.GIT_PASSWORD }} \
            -e PLUGIN_FORCE="true" \
            tencentcom/git-sync
