name: Sync to CNB
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part:
          # 组1：root文件+部分小目录
          - |
            .clang-format
            .clang-tidy
            .clangd
            .cursorignore
            .git-blame-ignore-revs
            .gitallowed
            .gitattributes
            .gitignore
            .gitmodules
            .gn
            .mailmap
            .rustfmt.toml
            .vpython3
            .yapfignore
            ATL_OWNERS
            AUTHORS
            BUILD.gn
            CODE_OF_CONDUCT.md
            CPPLINT.cfg
            CRYPTO_OWNERS
            DEPS
            DIR_METADATA
            LICENSE
            LICENSE.chromium_os
            OWNERS
            PRESUBMIT.py
            PRESUBMIT_test.py
            PRESUBMIT_test_mocks.py
            README.md
            SECURITY_OWNERS
            WATCHLISTS
            codereview.settings
            .github
            docs
            styleguide
            infra
            codelabs

          # 组2
          - |
            android_webview
            apps
            ash
            base
            build
            build_overrides
            buildtools
            cc
            chrome
            chromecast
            chromeos

          # 组3
          - |
            clank
            components
            content
            crypto
            dbus
            device
            extensions
            fuchsia_web
            gin
            google_apis
            gpu

          # 组4
          - |
            headless
            internal
            ios
            ios_internal
            ipc
            media
            mojo
            net
            pdf
            ppapi
            printing

          # 组5
          - |
            remoting
            rlz
            sandbox
            services
            signing_keys
            skia
            sql
            storage
            testing
            third_party

          # 组6
          - |
            tools
            ui
            url
            v8
            webkit
            webkit/data

    steps:
      - name: Sparse Checkout group
        run: |
          git init
          git remote add origin https://github.com/wubonetcn/chromium.git
          git config core.sparseCheckout true
          echo "${{ matrix.part }}" > .git/info/sparse-checkout
          git fetch --depth=1 origin main
          git checkout main

      - name: Sync ${{ matrix.part }} to CNB Repository
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/${{ secrets.GIT_TARGET }}.git" \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="cnb" \
            -e PLUGIN_PASSWORD=${{ secrets.GIT_PASSWORD }} \
            -e PLUGIN_FORCE="true" \
            tencentcom/git-sync
